#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# Initially hardcoded path, then it will be setup otherwise
N8S_PATH = C:\Users\Francesco\Documents\Nuvoton-8bit-SDCC\nuvoton-sdcc

PROJECT_NAME := helloworld


include $(N8S_PATH)/make/project.mk
